## 行列の計算

In [41]:
import numpy as np

A = np.array([[1,2], [-3,4]])
A

array([[ 1,  2],
       [-3,  4]])

In [42]:
A = np.array([[1,2,3], [-3,4,5]])
A

array([[ 1,  2,  3],
       [-3,  4,  5]])

In [43]:
B = np.array([[2,4,6], [-6,8,10]])
print(A+B)
print(A-B)

[[ 3  6  9]
 [-9 12 15]]
[[-1 -2 -3]
 [ 3 -4 -5]]


## 行列の掛け算

In [44]:
print(A*B) #対応する要素同士の掛け算
print(B.T) #行列Bの転置行列
print(np.dot(A,B.T)) #行列AとBの転置行列の掛け算

[[ 2  8 18]
 [18 32 50]]
[[ 2 -6]
 [ 4  8]
 [ 6 10]]
[[ 28  40]
 [ 40 100]]


In [45]:
A = np.array([[1,2], [-3,4]])
print(np.linalg.inv(A))
print(np.dot(A,np.linalg.inv(A)))

[[ 0.4 -0.2]
 [ 0.3  0.1]]
[[1.00000000e+00 2.77555756e-17]
 [0.00000000e+00 1.00000000e+00]]


In [46]:
print(np.linalg.det(A))

10.000000000000002


## 固有ベクトル、固有値

In [47]:
w,v = np.linalg.eig(A)
print('固有値=',w)
print('固有ベクトル=',v)
# 固有ベクトルは(0.387~-0.5j,0.77~+0j)と
# (0.387~+0.5j, 0.77~+0j)

固有値= [2.5+1.93649167j 2.5-1.93649167j]
固有ベクトル= [[0.38729833-0.5j 0.38729833+0.5j]
 [0.77459667+0.j  0.77459667-0.j ]]


## 対角化

In [48]:
# 前セルより、vに対角化行列
vinv = np.linalg.inv(v) #vの逆行列
vinv_A_v = np.dot(vinv, np.dot(A,v)) #v-1Av
print(vinv_A_v)

# (v-1Av)^n = v-1*A^n*v
# A^n = v*(v-1Av)^n*v

[[2.50000000e+00+1.93649167e+00j 2.22044605e-16+2.22044605e-16j]
 [4.44089210e-16-1.11022302e-16j 2.50000000e+00-1.93649167e+00j]]


# シス工の前の課題

In [66]:
A = np.array([[0.7,0.3],[0.6,0.4]])
# (1)固有値と固有ベクトル
# (2)nが0以上の整数で与えられる時、Aのn乗を計算するプログラム

- (1)

In [50]:
w,v = np.linalg.eig(A)
print('固有値=',w)
print('固有ベクトル=',v)

固有値= [1.  0.1]
固有ベクトル= [[ 0.70710678 -0.4472136 ]
 [ 0.70710678  0.89442719]]


- (2)

In [65]:
n = 3 #Aの3乘とする
result = np.array([[0,0],[0,0]])

In [64]:
for i in range(n):
    if i == 0:
        result = np.dot(A,A)
    else:
        result = np.dot(result,A)
result

array([[0.6667, 0.3333],
       [0.6666, 0.3334]])